# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycUWA8LzszsIw7UaHW5dLljd7hMFjMvX
"""

import pandas as pd
baza={
 "FISH":["Eshboyev Ilhom", "Aliyeva Gulnigor", "Abduhakimov Xursandbek", "Zokirova Anora", "Do'ltaboyev Muhammadjon", "Muhammadaliyev Abdullo", "Yusubov Temur", "Yo'ldoshev Xusniddin", "Mirzahamidov Jaloliddin", "Mamadaliyev Zikrullo"],
 "Yoshi":["18", "15", "14", "19", "22", "11", "15", "14", "9", "10"],
 "Maktabi":["21-maktab", "5-maktab", "20-maktab","39-maktab","56-maktab","58-maktab","225-maktab","201-maktab","46-maktab","89-maktab"],
 "Jinsi":["O'g'il bola", "qiz bola","O'g'il bola","qiz bola", "O'g'il bola","O'g'il bola","O'g'il bola","O'g'il bola","O'g'il bola","O'g'il bola"],
 "Manzili":["Samarqand", "Andijon", "Andijon", "Namangan", "Farg'ona", "Namangan", "Xorazm", "Farg'ona", "Namangan", "Farg'ona"]
 }
db=pd.DataFrame(baza)
print(db)

filtr=db[(db['Jinsi']=="qiz bola") & (db['Manzili']=="Namangan")]
print(filtr)